WIFI_SSID = "YOUR-WIFI-SSID"
WIFI_PSK = "YOUR-WIFI-PASSWORD"

PRINTER_USB_VID = "04b8" # EPSON
PRINTER_USB_PID = "0e15" # TM-T20II

MQTT_BROKER_IPV4 = "YOUR-MQTT-SERVER"
MQTT_BROKER_USER = "YOUR-MQTT-USERNAME"
MQTT_BROKER_PASS = "YOUR-MQTT-PASSWORD"
MQTT_BROKER_TOPIC = "printer/tm-t20ii/escpos"

#CODE_DEBUG = 1 # activate to wait on startup for USB-serial connection
